### ISSUE TITLE
New update this has a problem 

### ISSUE THREAD

**Issue by VSCODE-0000** [xtekky/TikTok-Report-Bot#21]
The program starts off by reporting the account, then it scrapes the videos, then it just goes crazy with errors. 

Exception in thread Thread-105 (reportVideo):
Exception in thread Thread-106 (reportVideo)Traceback (most recent call last):
Exception in thread Thread-107 (reportVideo)  File "C:\Program Files\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
:
Exception in thread :
Traceback (most recent call last):
Exception in thread Thread-108 (reportVideo)Traceback (most recent call last):
Thread-109 (reportVideo)  File "C:\Program Files\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
  File "C:\Program Files\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
:
:
    Exception in thread Traceback (most recent call last):
    self.run()Exception in thread Traceback (most recent call last):
Thread-110 (reportVideo)  File "C:\Program Files\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
self.run()Exception in thread Thread-111 (reportVideo)
Thread-112 (reportVideo)
  File "C:\Program Files\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    :
:
  File "C:\Program Files\Python311\Lib\threading.py", line 975, in run
  File "C:\Program Files\Python311\Lib\threading.py", line 975, in run
:
Exception in thread Traceback (most recent call last):
self.run()Traceback (most recent call last):
Traceback (most recent call last):
Thread-113 (reportVideo)
    :
  File "C:\Program Files\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
  File "C:\Program Files\Python311\Lib\threading.py", line 975, in run
Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
self.run()
  File "C:\Program Files\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
  File "C:\Program Files\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
  File "C:\Program Files\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "c:\Users\user\Desktop\TikTok-Report-Bot-main\main.py", line 32, in reportVideo
    self._target(*self._args, **self._kwargs)
  File "c:\Users\user\Desktop\TikTok-Report-Bot-main\main.py", line 32, in reportVideo
        self.run()self.run()
    self._target(*self._args, **self._kwargs)
      File "C:\Program Files\Python311\Lib\threading.py", line 975, in run

  File "C:\Program Files\Python311\Lib\threading.py", line 975, in run
      File "c:\Users\user\Desktop\TikTok-Report-Bot-main\main.py", line 32, in reportVideo
self.run()    self._target(*self._args, **self._kwargs)    'nickname'          : this.userInfo['userInfo']['user']['nickname'],
    self.run()
  File "C:\Program Files\Python311\Lib\threading.py", line 975, in run
'nickname'          : this.userInfo['userInfo']['user']['nickname'],

  File "c:\Users\user\Desktop\TikTok-Report-Bot-main\main.py", line 32, in reportVideo
self.run()   File "C:\Program Files\Python311\Lib\threading.py", line 975, in run

   File "C:\Program Files\Python311\Lib\threading.py", line 975, in run
     'nickname'          : this.userInfo['userInfo']['user']['nickname'],          self._target(*self._args, **self._kwargs)     
 'nickname'          : this.userInfo['userInfo']['user']['nickname'],

PS C:\Users\user\Desktop\TikTok-Report-Bot-main> 

```
Exception has occurred: TypeError
'NoneType' object is not subscriptable
  File "C:\Users\user\Desktop\TikTok-Report-Bot-main\main.py", line 32, in reportVideo
    'nickname'          : this.userInfo['userInfo']['user']['nickname'],
                          ~~~~~~~~~~~~~^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable

```

**Comment by stellastarrr** [comment]
I have the same exact issue PLEASE HELP!!

**Comment by Bigpapa100** [comment]
did you solve this problem?

**Comment by Bigpapa100** [comment]
> 
hello my friend, did you solve this error?
